Question
========
Consider the following R Markdown document:

```{r, error=TRUE, include=FALSE}
if ("package:tidyverse" %in% search()) {
  detach("package:tidyverse", unload = TRUE)
}
to_unload <- find("%>%")
lapply(to_unload, detach, unload = TRUE)
```

```{r, message=FALSE, error=TRUE}
library(ggplot2)

humans <- starwars %>%
  filter(species == "Human")
```


```{r, message=FALSE, error=TRUE, warning=FALSE}
library(tidyverse)

ggplot(humans, aes(x = mass, y = height)) + 
  geom_point()
```


What single change would fix both errors? 

Answerlist
----------
* Moving `library(tidyverse)` to the first row. 
* Changing the first pipe (`%>%`) to a plus (`+`)
* Removing `library(ggplot2)`
* Putting the second chunk first

Solution
========

Answerlist
----------
* True. 
* False. `filter()` does work with the `+`.
* False. This won't change anything. 
* False. This would result in `humans` being not found. 

Meta-information
================
extitle: error
exsection: rmarkdown
exname: rmarkdown-error
extype: schoice
exsolution: 1000
