---
chapter: data-II
author: "Ben Baumer"
date: "First edition"
difficulty: Medium
version: 0.1
tags:
- narrow to wide
- pivot
- dplyr
id: beech-come-shoe
output:
  pdf_document: default
  html_document:
    df_print: paged
---

(ref:beech-come-shoe) Exercise in file beech-come-shoe

```{r beech-come-shoe-default, include = FALSE}
mdsr2exercises::setup()
```

TITLE GOES HERE: Generate the code to convert the following data frame to wide format.

```{r warning = FALSE, echo = FALSE, message= FALSE}
library(mdsr)
library(mosaic)
library(readr)
library(tidyr)
library(xtable)
df <- tibble(
  id = c(1, 1, 2, 2, 3, 3, 4, 4, 5, 5),
  sex = c("M", "M", "F", "F", "F", "F", "M", "M", "M", "M"),
  grp = rep(c("A", "B"), 5),
  left = c(0.1, 0.2, 0.3, 0.4, 0.15, 0.25, 0.6, 0.65, 0.71, 0.79),
  right = c(0.1, 0.25, 0.3, 0.35, 0.18, 0.25, 0.6, 0.6, 0.71, 0.79) + 0.1
)
sumdf <- df %>%
  group_by(grp, sex) %>%
  summarize(
    meanL = mean(left), sdL = sd(left),
    meanR = mean(right), sdR = sd(right)
  ) %>%
  ungroup()
```

```{r, echo = FALSE}
sumdf
```

The result should look like the following display.

```{r beech-come-shoe-1, echo=FALSE, message = FALSE}
sumdf %>%
  pivot_longer(
    names_to = "temp", 
    values_to = "vals", 
    col = c(meanL, meanR, sdL, sdR)
  ) %>%
  unite(col = "temp1", sex, temp, sep = ".") %>%
  pivot_wider(names_from = temp1, values_from = vals)
```

Hint: use `r mdsr2exercises::func_macro(pivot_longer)` in conjunction with `r mdsr2exercises::func_macro(pivot_wider)`.

<!--begin-answer-->
```{r beech-come-shoe-1, echo=TRUE}
```
<!--end-answer-->

