---
chapter: "data-II"
author: ""
difficulty: "Medium"
date: 2020-06-14 
version: 0.1
tags: [wikipedia, scraping, visualization, ggplot, dplyr]
id: beech-blow-bowl
---

```{r beech-blow-bowl-default, include = FALSE}
mdsr2exercises::setup()
library(tidyverse)
library(mdsr)
```

TITLE GOES HERE:   Find an interesting Wikipedia page with a table, scrape the data from it, and generate a figure that tells an interesting story. Include an interpretation of the figure.
 
 <!--begin-answer-->

Answers will vary.
Here is one example.
 
```{r,message=FALSE}
library(rvest)
library(tidyr)
my_html <-
  read_html("http://en.wikipedia.org/wiki/List_of_highest-grossing_films")
tables <- my_html %>% html_nodes(css = "table")
movies <- html_table(tables[[2]])
names(movies)[3] <- "Gross2019dollars"
movies <- movies %>%
  mutate(
    GrossMil = readr::parse_number(Gross2019dollars) / 1000000,
    Year = readr::parse_number(as.character(Year))
  )
movies
ggplot(data = movies, aes(x = Year, y = GrossMil)) +
  geom_point() +
  theme(legend.position = "none") +
  ylab("Gross (in millions of US 2019$)")
```
 
<!--end-answer-->


