---
chapter: "dataviz-III"
author: "Nicholas Horton"
difficulty: "Hard"
date: 2020-08-16 
version: 0.1
tags: [macleish, wikipedia, visualization, ggplot]
id: cheetah-see-pen
---

```{r cheetah-see-pen-default, include = FALSE}
library(tidyverse)
library(mdsr)
mdsr2exercises::setup()
```

TITLE GOES HERE:	Repeat the earlier question using the weather data from the MacLeish field station, but include context on major storms listed on the Wikipedia pages: [2014--2015 North American Winter](https://en.wikipedia.org/wiki/2014%E2%80%9315_North_American_winter) and
[2015--2016 North American Winter](https://en.wikipedia.org/wiki/2015%E2%80%9316_North_American_winter).

 <!--begin-answer-->
 
```{r message = FALSE}
library(macleish)
equinoxes <- tibble(
  Date = as.Date(c("2015-03-21", "2015-06-20", "2015-09-21", "2015-12-20")),
  season = c("Winter ", "Spring ", "Summer ", "Fall "))
storms <- tibble(
  Date = as.Date(c("2015-02-08", "2015-02-14", "2015-12-29")),
  name = c("Early February winter storm", "Mid-February blizzard", "Post-Christmas storm complex"))
whately_2015 <- whately_2015 |>
  mutate(Date = as.Date(when))
weather_plot <- ggplot(data = whately_2015,
  aes(x = Date, y = temperature)) +
  labs(y = "Temperature (degrees C)") + 
  geom_vline(data = equinoxes, color = "darkgray",
             aes(xintercept = as.numeric(Date))) +
  geom_vline(data = storms, color = "red",
             aes(xintercept = as.numeric(Date))) +
  geom_text(data = equinoxes, aes(y = 33, label = season, hjust = "right")) +
  geom_text(data = storms, aes(y = c(25, 20, 25), label = name, hjust = c("left", "left", "right")), color = "red") +
  geom_line(size = 0.3, color = "darkgray") + geom_smooth() +
  scale_x_date()
weather_plot
```

<!--end-answer-->
