---
chapter: "text"
author: "Nicholas J. Horton"
difficulty: "Hard"
date: 2020-06-25 
version: 0.1
tags: [dickinsonpoems, text, poetry, sentiment analysis, onlineonly]
id: lion-forget-ring
---

```{r lion-forget-ring-default, include = FALSE}
mdsr2exercises::setup()
library(DickinsonPoems)
```

TITLE GOES HERE: Given the dataframe of Emily Dickinson poems in the `r pkg_macro(DickinsonPoems)` package, perform sentiment analysis and identify any interesting insights about her work overall.  

```{r lion-forget-ring-load-poems}
library(tidyverse)
# remotes::install_github("Amherst-Statistics/DickinsonPoems")
library(DickinsonPoems)
library(tidytext)
poems_df <- list_poems() |>
  purrr::map(get_poem) |>
  unlist() |>
  enframe(value = "words") |>
  unnest_tokens(word, words)
```

<!--begin-answer-->

```{r ling-forget-ring-begin-ans, message=FALSE}
poems_df |>
  filter(!word %in% stop_words$word) |>
  count(word, sort = TRUE) |>
  head(15)

poems_df |>
  inner_join(get_sentiments("bing")) |>
  count(word, sentiment, sort = TRUE) |>
  head(10)

poems_df |>
  inner_join(get_sentiments("afinn")) |>
  summarize(afinn = sum(value))
```

```{r download-sentiments}
# need to run this once to install the NRC lexicon
sentiments <- get_sentiments("nrc")
```

```{r top-word}
poems_df |>
  inner_join(sentiments) |>
  group_by(sentiment) |>
  count(sentiment) |>
  arrange(desc(n)) |>
  ungroup() |>
  top_n(1)
```

<!--end-answer-->


