---
chapter: "dataviz-III"
author: "Nicholas Horton"
difficulty: "Easy"
date: 2020-09-08 
version: 0.1
tags: [shiny, shiny apps, ggthemes, visualization]
id: maple-tug-drawer
---

```{r maple-tug-drawer-default, include = FALSE}
mdsr2exercises::setup()
```

TITLE GOES HERE:    Modify the Shiny app that displays the frequency of Beatles names over time so that it has a `checkboxInput()` widget that uses the `theme_tufte()` theme from the `ggthemes` package. 

<!--begin-answer-->

Here is the `server.R` file:

```{r eval = FALSE}
# server.R
library(tidyverse)
library(ggthemes)
library(babynames)
library(shiny)
Beatles <- babynames |>
  filter(name %in% c("John", "Paul", "George", "Ringo") & sex == "M")

shinyServer(
  function(input, output) {
    output$plot <- renderPlot({
      ds <- Beatles |>
        filter(
          year >= input$startyear, year <= input$endyear,
          name %in% input$names
        )
      g <- ggplot(data = ds, aes(x = year, y = prop, color = name)) +
        geom_line(size = 2)
      if (input$tufte_theme) {
        g <- g + theme_tufte()
      }
      g
    })
  }
)
```

Here is the `ui.R` file:

```{r eval = FALSE}
# ui.R
beatles_names <- c("John", "Paul", "George", "Ringo")

shinyUI(
  bootstrapPage(
    h3("Frequency of Beatles names over time"),
    numericInput(
      "startyear", "Enter starting year",
      value = 1960, min = 1880, max = 2014, step = 1
    ),
    numericInput(
      "endyear", "Enter ending year",
      value = 1970, min = 1881, max = 2014, step = 1
    ),
    checkboxInput(
      "tufte_theme", "Use Tufte theme?", FALSE
    ),
    checkboxGroupInput(
      'names', 'Names to display:',
      sort(unique(beatles_names)),
      selected = c("George", "Paul")
    ),
    plotOutput("plot")
  )
)
```

<!--end-answer-->

