---
chapter: "ethics"
author: ""
difficulty: "Medium"
date: 2020-07-13 
version: 0.1
tags: [ethics, privacy, confidentiality, penalties]
id: maple-choose-spoon
---

```{r maple-choose-spoon-default, include = FALSE}
mdsr2exercises::setup()
```

TITLE GOES HERE: In the United States, the Confidential Information Protection and Statistical Efficiency Act (CIPSEA) governs the confidentiality of data collected by agencies such as the Bureau of Labor Statistics and the Census Bureau.  What are the penalties for willful and knowing disclosure of protected information to 
unauthorized persons?


  <!--begin-answer-->

The Bureau of Labor Statistics states that its employees, agents, and partner statistical agencies will use the information provided by its respondents for statistical purposes only and will hold the information in confidence to the full extent permitted by law. Willful and knowing disclosure of protected data to unauthorized persons is a felony punishable by up to five years imprisonment and up to a $250,000 fine.
  <!--end-answer-->


