---
chapter: "dataviz-I"
author: ""
difficulty: "Medium"
date: 2020-07-13 
version: 0.1
tags: [visualization, data graphics, visual cues, interpretation]
id: seaweed-buy-plant
---

```{r seaweed-buy-plant-default, include = FALSE}
mdsr2exercises::setup()
```

TITLE GOES HERE: Consider the data graphic http://tinyurl.com/nytimes-unplanned about birth control methods.

a. What quantity is being shown on the $y$-axis of each plot?
b. List the variables displayed in the data graphic, along with the units and a few typical values for each. 
c. List the visual cues used in the data graphic and explain how each visual cue is linked to each variable.
d. Examine the graphic carefully. Describe, in words, what *information* you think the data graphic conveys. Do not just summarize the *data*---interpret the data in the context of the problem and tell us what it means. 
(Note: *information* is meaningful to human beings---it is not the same thing as *data*.)


  <!--begin-answer-->
  
-  The number of women out of 100 who will have an unplanned preganancy. 
-  Variables:
    -  `years`: units of years: 1, 2, 3, ...
    -  `number_of_women`: units of people: 1, 2, 3, ...
    -  `method`: categorical: spermicides, etc.
    -  `use_type`: categorical: typical, perfect
 -  Mappings:
    -  horizontal position is mapped to `year`
    -  vertical position is mapped to `number_of_women`
    -  facets are mapped to `method`
    -  lines/shapes are mapped to `use_type`
    -  color/shade is mapped to `number_of_women`
-  Most any birth control methods will likely fail at least once with typical use over a 10 year period. However, Depo-Provera and the pill are the most effective, especially with perfect use. 
  
  <!--end-answer-->


