---
chapter: "learning-I"
author: "Nicholas Horton"
difficulty: "Easy"
date: 2020-10-02 
version: 0.1
tags: [mosaic, decision trees]
id: snail-ring-shirt
---

```{r snail-ring-shirt-default, include = FALSE}
mdsr2exercises::setup()
```

TITLE GOES HERE: Use the `HELPrct` data from the `r pkg_macro(mosaicData)` to fit a tree model to the following predictors: `age`, `sex`, `cesd`, and `substance`.

a. Plot the resulting tree and interpret the results.

b. What is the accuracy of your decision tree?

 <!--begin-answer-->

```{r message = FALSE}
library(tidymodels)
library(mosaicData)
form <- formula("homeless ~ age + sex + cesd + substance")
mod_tree <- decision_tree(mode = "classification") |>
   set_engine("rpart") |>
   fit(form, data = HELPrct)
mod_tree
```

```{r message = FALSE}
HELPrct <- HELPrct |>
   mutate(predicted = 
             predict(mod_tree, new_data = HELPrct) |>
             pull(.pred_class)
   )
mosaic::tally(~ homeless, format = "prop", data = HELPrct)
mosaic::tally(~ predicted + homeless, data = HELPrct)
```

The accuracy is poor: only 67% of the observations were correctly classified.

```{r}
(121 + 182) / (121 + 62 + 88 + 182)
```
 
<!--end-answer-->

 
